#!/bin/bash

while [ $# -gt 0 ]; do
  case "$1" in
    --interactive )
      ifconfig
      echo -n "Please enter domain name (e.g. myexample.com) : "; read DOMAIN
      echo -n "Please enter nic device name (e.g. ens0) : "; read NIC
      echo -n "Please enter upstream dns addr: "; read NEXT_DNS
      echo -n "Please enter default gateway addr: "; read GATEWAY
      echo -n "Please enter ntp server addr: "; read NTP
      echo -n "Please enter dhcp range (e.g. x.x.x.a,x.x.x.b): "; read DHCP_RNG
#      echo -n "Please enter tftp range (e.g. x.x.x.a,x.x.x.b): "; read TFTP_RNG
      
      shift
      ;;
    --help )
      echo "Example: $0 --domain <domain> --gw <gateway> --ntp <ntp addr> --dhcprng <dhcp range: (x.x.x.a,x.x.x.b)>"
      #echo "Example: $0 --domain <domain> --gw <gateway> --ntp <ntp addr> --dhcprng <dhcp range: (x.x.x.a,x.x.x.b)> --tftp_rng <tftp range: (x.x.x.a,x.x.x.b)>"
      shift
      exit
      ;;
    --domain ) DOMAIN="$2"; echo "Read $1: $DOMAIN"; shift; shift
      ;;
    --nic ) NIC="$2"; echo "Read $1: $NIC"; shift; shift
      ;;
    --nextdns ) NEXT_DNS="$2"; echo "Read $1: $NEXT_DNS"; shift; shift
      ;;
    --gw ) GATEWAY="$2"; echo "Read $1: $GATEWAY"; shift; shift
      ;;
    --ntp ) NTP="$2"; echo "Read: $1: $NTP"; shift; shift
      ;;
    --dhcprng ) DHCP_RNG="$2"; echo "Read: $1: $DHCP_RNG"; shift; shift
      ;;
#    --tftprng ) TFTP_RNG="$2"; echo "Read: $1: $TFTP_RNG"; shift; shift
#      ;;
    * ) echo "$#"; shift;;
  esac
done

## Check if all arguments are set
if [ -z "$DOMAIN" ] || [ -z "$GATEWAY" ]; then
  echo "Insufficient arguments. Please use --help for help".
  exit
fi

# Installing dnsmasq
sudo apt-get purge -y dnsmasq
sudo apt-get install -y dnsmasq

FILE_DNSMASQ_CONF="/etc/dnsmasq.conf"
FILE_DNSMASQ_HOSTS="/etc/dnsmasq_static_hosts.conf" 

# Setup/config dnsmasq as DNS DHCP

sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.backup

cat <<CFG | sudo tee /etc/dnsmasq.conf
domain-needed
bogus-priv
no-resolv
no-poll
interface=$NIC
# Set one or more dns server when addresses aren't local
#server=/example.com/192.168.0.5
server=$NEXT_DNS 
server=8.8.8.8
#server=208.67.220.220
# Our local domain, queries in these domains are answered from /etc/hosts or the static-hosts files.
local=/$DOMAIN/ 
# Use this force an address for the specified domains. e.g to block adverts force doubleclck.net to localhost
address=/doubleclick.net/127.0.0.1
#no-hosts # Telling not to use /etc/hosts
#addn-hosts=$FILE_DNSMASQ_HOSTS # Use this hosts file instead
# So we can see our local hosts via our home domain without having to repeatedly specify the domain in our /etc/hosts file. 
expand-hosts 
# My local domain name. It will tell the DHCP server which host to give out IP addresses for 
domain=$DOMAIN
# DHCP setting 
dhcp-range=$NIC,$DHCP_RNG,72h
#dhcp-range=tftp,$TFTP_RNG  
#dhcp-host=gw,$GATEWAY,36h # Any host name 'gw' will get this address
dhcp-option=option:router,$GATEWAY
dhcp-option=option:ntp-server,$NTP
dhcp-option=19,0 # ip-forwarding off
#dhcp-option=44,192.168.0.5 # set netbios-over-TCP/IP aka WINS
#dhcp-option=45,192.168.0.5 # netbios datagram distribution server
#dhcp-option=46,8           # netbios node type  
CFG

# Config hosts file
cat <<CFG | sudo tee -a $FILE_DNSMASQ_HOSTS
#192.168.0.8  mail mail.example.com
#192.168.0.9  smtp smtp.example.com
#192.168.0.120 mythtvbox mythtvbox.example.com
# Generated by ktaiga's script
CFG


#Testing dnsmasq config
dnsmasq --test


#Starting the service

#sudo service dnsmasq start
#sudo service dnsmasq stop
sudo service dnsmasq restart
